### PR TITLE
Todo-LIst add & remove function

### PR DESCRIPTION
**Pull request by Oscah01**
- Add event listener to the checkbox.
 - Update items object's value for completed key upon user actions.
 - Add a function for the "Clear all completed" button
 - update config files

### CODE REVIEW

**Review by MaganaAsiati — CHANGES_REQUESTED** [review]
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @Oscah01 , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close-gif-4

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- Kindly make sure that you add some functionality to the application to make it interactive. The user will be able to mark task completion by selecting the corresponding checkbox. The updated tasks list will be stored in local storage. All the elements of the user interface will be fully functional and the application should be completed at this stage. please ensure that you can be able to add, remove, and have the checkbox to mark the task complete. on my side, I was not able to add a task and check those functionalities please fix that :+1: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ]  [OPTIONAL] Kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Oscah01** [comment]
> # STATUS: Required Changes 
> ## Hi @Oscah01 , I'm @MaganaAsiati, your reviewer for this PR 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> so-close-gif-4 [ so-close-gif-4 ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif) [ ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> 
> ## Highlights
> * Descriptive README file  heavy_check_mark👨🏻‍💻
> * Great work using the right GitHub Flow.heavy_check_mark
> * No Linter errors heavy_check_mark
> 
> ## Required Changes 
> * Kindly make sure that you add some functionality to the application to make it interactive. The user will be able to mark task completion by selecting the corresponding checkbox. The updated tasks list will be stored in local storage. All the elements of the user interface will be fully functional and the application should be completed at this stage. please ensure that you can be able to add, remove, and have the checkbox to mark the task complete. on my side, I was not able to add a task and check those functionalities please fix that +1
>   _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
> 
> * [ ]  [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. heavy_check_mark👨🏻‍💻
> * [ ]   [OPTIONAL] Kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone heavy_check_mark👨🏻‍💻
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

I think im my side the app is working fine, may be you did not check the correct branch final-todoList then run npm run dev

**Comment by Oscah01** [comment]
> > # STATUS: Required Changes
> > ## Hi @Oscah01 , I'm @MaganaAsiati, your reviewer for this PR
> > Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> > so-close-gif-4
> >       
> >         [
> >           
> >             so-close-gif-4
> >           
> >         ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> >         
> >        [ so-close-gif-4 ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> >       
> >         [
> >           
> >             so-close-gif-4
> >           
> >         ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
> > ## Highlights
> > 
> > * Descriptive README file  heavy_check_mark👨🏻‍💻
> > * Great work using the right GitHub Flow.heavy_check_mark
> > * No Linter errors heavy_check_mark
> > 
> > ## Required Changes
> > 
> > * Kindly make sure that you add some functionality to the application to make it interactive. The user will be able to mark task completion by selecting the corresponding checkbox. The updated tasks list will be stored in local storage. All the elements of the user interface will be fully functional and the application should be completed at this stage. please ensure that you can be able to add, remove, and have the checkbox to mark the task complete. on my side, I was not able to add a task and check those functionalities please fix that +1
> >   _Check the comments under the review._
> > 
> > ## 
Screenshot_2023-01-21_10_02_41
Optional suggestions
> > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
> > 
> > * [ ]   [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. heavy_check_mark👨🏻‍💻
> > * [ ]    [OPTIONAL] Kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone heavy_check_mark👨🏻‍💻
> > 
> > Cheers and Happy coding!clapclapclap
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> I think im my side the app is working fine, may be you did not check the correct branch final-todoList then run npm run dev

Screenshot_2023-01-21_10_02_41
bd3f-5c94916556
Screenshot_2023-01-21_10_31_27
36.png)

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 @Oscah01, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You well to make the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
